/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'bg-primary': '#000000',
        'bg-card': 'rgba(255, 255, 255, 0.025)',
        'bg-card-hover': 'rgba(255, 255, 255, 0.04)',
        'bg-glass': 'rgba(255, 255, 255, 0.03)',
        'bg-elevated': '#0A0A0A',
        'bg-hover': '#111111',
        'bg-secondary': '#0A0A0A',
        'bg-tertiary': '#111111',
        'border-subtle': 'rgba(255, 255, 255, 0.06)',
        'border-default': 'rgba(255, 255, 255, 0.1)',
        'border-focus': '#6366F1',
        'text-primary': '#FFFFFF',
        'text-secondary': '#A1A1AA',
        'text-muted': '#71717A',
        'accent-primary': '#6366F1',
        'accent-hover': '#818CF8',
        'accent-active': '#4F46E5',
        'accent-red': '#EF4444',
        'accent-blue': '#3B82F6',
        'accent-green': '#22C55E',
        'accent-violet': '#8B5CF6',
        'accent-pink': '#EC4899',
        'accent-cyan': '#06B6D4',
        'accent-orange': '#F97316',
        'accent-yellow': '#EAB308',
        'success': '#22C55E',
        'warning': '#F59E0B',
        'danger': '#EF4444',
        'info': '#3B82F6',
        'chart-1': '#6366F1',
        'chart-2': '#3B82F6',
        'chart-3': '#22C55E',
        'chart-4': '#F59E0B',
        'chart-5': '#EC4899',
        'chart-6': '#8B5CF6',
        'chart-7': '#06B6D4',
        'chart-8': '#F97316',
        'glow-violet': 'rgba(139, 92, 246, 0.4)',
        'glow-blue': 'rgba(59, 130, 246, 0.4)',
        'glow-green': 'rgba(34, 197, 94, 0.4)',
        'glow-orange': 'rgba(249, 115, 22, 0.4)',
        'glow-pink': 'rgba(236, 72, 153, 0.4)',
        'glow-cyan': 'rgba(6, 182, 212, 0.4)',
        'glow-red': 'rgba(239, 68, 68, 0.4)',
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        'display': ['"Space Grotesk"', 'system-ui', 'sans-serif'],
        'body': ['"Inter"', 'system-ui', 'sans-serif'],
        'accent': ['"Playfair Display"', 'Georgia', 'serif'],
        'mono': ['"JetBrains Mono"', 'monospace'],
        'inter': ['Inter', 'sans-serif'],
      },
      borderRadius: {
        xl: "calc(var(--radius) + 4px)",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xs: "calc(var(--radius) - 6px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "skeleton-pulse": {
          "0%, 100%": { opacity: "0.4" },
          "50%": { opacity: "0.7" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "skeleton-pulse": "skeleton-pulse 1.5s ease-in-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
